### ISSUE TITLE
Overhaul UI Of Drawing Canvas.

### ISSUE THREAD

**Issue by MananAgr2003** [Subhradeep10/Amazing_Web_Projects#13]
Hey There! I Would Like To redesign and implement the drawing canvas page kindly assign me this issue

**Comment by Subhradeep10** [comment]
@MananAgr2003 Assign to you, Go ahead

**Comment by Subhradeep10** [comment]
@MananAgr2003 Any updates? Otherwise I will close the issue

**Comment by MananAgr2003** [comment]
Yes still woking Have been a little busy will update asap

**Comment by Subhradeep10** [comment]
Issue is closed due to no response
