### ISSUE TITLE
Favicon is Needed

### ISSUE THREAD

**Issue by Subhradeep10** [Subhradeep10/Amazing_Web_Projects#3]
Someone add favicon to the site

**Comment by gokhalevedant06** [comment]
Hi, I would like to work on this issue

**Comment by Subhradeep10** [comment]
@gokhalevedant06 Go Ahead

**Comment by gokhalevedant06** [comment]
Anything else to be done ?

**Comment by Subhradeep10** [comment]
If you want , You can add your own web dev projects in the repo and share the screenshot in PL
