### ISSUE TITLE
tic-tac-toe

### ISSUE THREAD

**Issue by Laraibnehal** [Subhradeep10/Amazing_Web_Projects#31]

**Comment by hardiksharma02** [comment]
is this for hacktober fest, and can we get some description

**Comment by Subhradeep10** [comment]
@Laraibnehal want to work on the issue, or shall I assign to someone else?

**Comment by Laraibnehal** [comment]
Yes i wanna work

**Comment by Subhradeep10** [comment]
@Laraibnehal Okk assign to you

**Comment by Subhradeep10** [comment]
@Sonal-Maurya @hardiksharma02 You guys, can create some other issues and can start working on that..I will assign it to you
