### ISSUE TITLE
Snake game 

### ISSUE THREAD

**Issue by A-R-M-028** [Subhradeep10/Amazing_Web_Projects#44]
Hey i want to contribute in your repo on a snake game in python ,
plese revert me, shall i go ahead with it or not?

**Comment by Subhradeep10** [comment]
@A-R-M-028 Assign to you

**Comment by Subhradeep10** [comment]
@A-R-M-028 any updates!?

**Comment by A-R-M-028** [comment]
_Working on, required 2 or 3 days_
