### ISSUE TITLE
Enhancing designs of existing projects

### ISSUE THREAD

**Issue by RishabhJain0721** [Subhradeep10/Amazing_Web_Projects#47]
## Hi
@Subhradeep10 I wish to enhance the styling of existing projects whose UI aren't looking very good..like the button press counter,Lorem generator and adding social media icons on product laundhing website.
Please assign this task to me.

**Comment by Subhradeep10** [comment]
@RishabhJain0721 assign to you

**Comment by RishabhJain0721** [comment]
@Subhradeep10 I have made a PR. Please review it.
