### ISSUE TITLE
Make a simple shooting game using Web Dev Skills

### ISSUE THREAD

**Issue by AryamanAdivyaSingh47** [Subhradeep10/Amazing_Web_Projects#59]
I will be making a simple 2d simple shooting game using 
1.HTML
2.CSS
3JavaScript

@Subhradeep10  Would like if you would assign me this project

**Comment by Subhradeep10** [comment]
@AryamanAdivyaSingh47 Go ahead, assigned to you

**Comment by Subhradeep10** [comment]
@AryamanAdivyaSingh47 Any updates!?

**Comment by Ghat0tkach** [comment]
hey is the issue still open? i would love to contribute in this :)

**Comment by Subhradeep10** [comment]
@Ghat0tkach Go ahead, Assigned to you

**Comment by AryamanAdivyaSingh47** [comment]
Yeah, Actually the project will be going slow for a week or so ch I have
tests going on in college. You know.
